#!/bin/sh
# Xsetup - run as root before the login dialog appears

xrandr --output HDMI-A-0 --off &
xrandr --output DisplayPort-2 --mode 1920x1080 --rate 164.92 &
x11vnc -many -display :0 -loop -noxdamage -shared -xkb &
